#!/usr/bin/env python
import rox, os, sys
from optparse import OptionParser
from rox import g

if sys.version_info < (2, 4):
	raise Exception('0publish-gui requires Python >= 2.4. You have %s' %
		'.'.join(map(str, sys.version_info)))

import gtk.glade
from main import FeedEditor, choose_feed

version = '0.4'
parser = OptionParser(usage="usage: %prog [options] interface")
parser.add_option("-V", "--version", help="display version information", action='store_true')
(options, args) = parser.parse_args()

if options.version:
	print "0publish-gui (zero-install) " + version
	print "Copyright (C) 2007 Thomas Leonard"
	print "This program comes with ABSOLUTELY NO WARRANTY,"
	print "to the extent permitted by law."
	print "You may redistribute copies of this program"
	print "under the terms of the GNU General Public License."
	print "For more information about these matters, see the file named COPYING."
	sys.exit(0)

if args:
	for file in args:
		editor = FeedEditor(file)
		editor.window.show()
		#editor.add_version()
else:
	editor = choose_feed()
	editor.window.show()

rox.mainloop()
