#!/usr/bin/env python
import rox, os, sys
from rox import g

if sys.version_info < (2, 4):
	raise Exception('0publish-gui requires Python >= 2.4. You have %s' %
		'.'.join(map(str, sys.version_info)))

import gtk.glade
from main import FeedEditor, choose_feed

RESPONSE_SAVE = 0

args = sys.argv[1:]

if args:
	for file in args:
		editor = FeedEditor(file)
		editor.window.show()
		#editor.add_version()
else:
	editor = choose_feed()
	editor.window.show()

rox.mainloop()
