#!/usr/bin/env python
import rox, os, sys
from rox import g
import gtk.glade
from main import FeedEditor, choose_feed

RESPONSE_SAVE = 0

args = sys.argv[1:]

if args:
	for file in args:
		editor = FeedEditor(file)
		editor.window.show()
else:
	editor = choose_feed()
	editor.window.show()

rox.mainloop()
